init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

environment:
  nodejs_version: "10.10.0"

cache:
 - "%LOCALAPPDATA%\\Yarn"

# Install scripts. (runs after repo cloning)
install:
  # install latest dotnet core 3 preview
  - cmd: choco install dotnetcore-sdk --pre
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install

os: Visual Studio 2017

build_script:
  - cmd: npm run build

test: off